In [8]:
import yfinance as yf

In [9]:
# Download historical data for a stock
msft = yf.Ticker("MSFT")
msft_data = msft.history(period="max")

c:\Users\Asus\AppData\Local\Programs\Python\Python311\Lib\site-packages\yfinance\utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

In [10]:
msft_data.head(10)

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13 00:00:00-05:00,0.054893,0.062965,0.054893,0.060274,1031788800,0.0,0.0
1986-03-14 00:00:00-05:00,0.060274,0.063504,0.060274,0.062427,308160000,0.0,0.0
1986-03-17 00:00:00-05:00,0.062427,0.064042,0.062427,0.063504,133171200,0.0,0.0
1986-03-18 00:00:00-05:00,0.063504,0.064042,0.061350,0.061889,67766400,0.0,0.0
1986-03-19 00:00:00-05:00,0.061889,0.062427,0.060274,0.060812,47894400,0.0,0.0
1986-03-20 00:00:00-05:00,0.060812,0.060812,0.058660,0.059198,58435200,0.0,0.0
1986-03-21 00:00:00-05:00,0.059198,0.060274,0.056507,0.057583,59990400,0.0,0.0
1986-03-24 00:00:00-05:00,0.057584,0.057584,0.055431,0.055969,65289600,0.0,0.0
1986-03-25 00:00:00-05:00,0.055969,0.057045,0.055431,0.057045,32083200,0.0,0.0
1986-03-26 00:00:00-05:00,0.057045,0.059198,0.056507,0.058660,22752000,0.0,0.0

# Author
Jitein Rawat